Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,7 +40,26 @@ jobs:
           pm2 restart my-nextjs-app --update-env || { echo 'PM2 restart failed'; exit 1; }; \
           pm2 save || { echo 'PM2 save failed'; exit 1; }; \
           echo 'Deployment completed successfully.'; \
-          "
+          "- name: Execute deployment commands
+          env:
+            SERVER_IP: ${{ secrets.SERVER_IP }}
+            SERVER_USER: ${{ secrets.SERVER_USER }}
+          run: |
+            ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -vvv -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "\
+            echo 'Deploying application...'; \
+            export NVM_DIR=\"/root/.nvm\"; \
+            [ -s \"/root/.nvm/nvm.sh\" ] && . \"/root/.nvm/nvm.sh\" || { echo 'Failed to load NVM'; exit 1; }; \
+            nvm use 18 || { echo 'Failed to switch Node version'; exit 1; }; \
+            cd /home/ec2-user/labx || { echo 'Directory not found'; exit 1; }; \
+            git stash --include-untracked; \
+            git pull || { echo 'Git pull failed'; exit 1; }; \
+            npm install || { echo 'NPM install failed'; exit 1; }; \
+            npm run build || { echo 'NPM build failed'; exit 1; }; \
+            pm2 restart my-nextjs-app --update-env || { echo 'PM2 restart failed'; exit 1; }; \
+            pm2 save || { echo 'PM2 save failed'; exit 1; }; \
+            echo 'Deployment completed successfully.'; \
+    "
+
 
       - name: Debug SSH connection
         if: failure()  # This step will run only if the previous steps fail
