Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,15 +39,16 @@ jobs:
           ssh -T -o BatchMode=yes -o StrictHostKeyChecking=no -vvv -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "\
           echo 'Deploying application...'; \
           export NVM_DIR=\"/root/.nvm\"; \
-          [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"; \
-          nvm use 18; \
-          cd /home/ec2-user/labx || exit 1; \
+          [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\" || { echo 'Failed to load NVM'; exit 1; }; \
+          export PATH=\$PATH:/usr/local/bin; \
+          nvm use 18 || { echo 'Failed to switch Node version'; exit 1; }; \
+          cd /home/ec2-user/labx || { echo 'Directory not found'; exit 1; }; \
           git stash --include-untracked; \
-          git pull; \
-          npm install; \
-          npm run build; \
-          pm2 restart my-nextjs-app --update-env; \
-          pm2 save; \
+          git pull || { echo 'Git pull failed'; exit 1; }; \
+          npm install || { echo 'NPM install failed'; exit 1; }; \
+          npm run build || { echo 'NPM build failed'; exit 1; }; \
+          pm2 restart my-nextjs-app --update-env || { echo 'PM2 restart failed'; exit 1; }; \
+          pm2 save || { echo 'PM2 save failed'; exit 1; }; \
           echo 'Deployment completed successfully.'; \
           "
 
